// ignore_for_file: constant_identifier_names
enum ExaminationType {
  BREAST_SELF,
  COLONOSCOPY,
  DENTIST,
  DERMATOLOGIST,
  GENERAL_PRACTITIONER,
  GYNECOLOGIST,
  MAMMOGRAM,
  OPHTHALMOLOGIST,
  TESTICULAR_SELF,
  TOKS,
  ULTRASOUND_BREAST,
  UROLOGIST,
  VENEREAL_DISEASES,
}
